import { spawn } from "node:child_process";
const child = spawn(
  process.execPath,
  [
    "node_modules/next/dist/bin/next",
    "dev",
    "--hostname",
    "127.0.0.1",
    "--port",
    process.env.PORT ?? "3001",
  ],
  {
    stdio: "inherit",
    env: {
      ...process.env,
      EXITCHECK_MODE: "fixture",
      EXITCHECK_DATABASE: "sqlite",
      MONITORING_WORKFLOW_ENABLED: "false",
      JUPITER_API_KEY: "",
      DEEPSEEK_API_KEY: "",
      RESEARCH_PROVIDER: "gemini",
      GEMINI_API_KEY: "",
      GEMINI_API_KEY_1: "",
      GEMINI_API_KEY_2: "",
      GEMINI_API_KEY_3: "",
      SOLANA_RPC_URL: "",
      TURSO_DATABASE_URL: "",
      TURSO_AUTH_TOKEN: "",
      ENABLE_LIVE_EXECUTION: "false",
      ALLOWED_PROGRAM_IDS: "",
      SHADOW_COLLECTOR_ENABLED: "false",
      MARKET_RECORDER_ENABLED: "false",
      AGENT_COLLECTOR_ENABLED: "false",
      ACTION_DB_PATH: "./test-results/fixture-actions.sqlite",
      SHADOW_DB_PATH: "./test-results/fixture-research.sqlite",
      APP_ORIGIN: `http://127.0.0.1:${process.env.PORT ?? "3001"}`,
    },
  },
);
child.on("exit", (code) => process.exit(code ?? 0));
